### ISSUE TITLE
Thanks and one correction/addition

### ISSUE THREAD

**Issue by heyudude** [Sir-Quickly/Yato_Control_Interface#1]
Hi,

Thanks for the PCB! Ordered it after adding the bottom mask to the layout (it was not selected) so the gerber files where generated correct. I do not know if it is something I did wrong or you can select by default in the KiCad project / board setup for others. 

Any tips when I got the PCB? I read the German forum also so I know the support source ;)

**Comment by Sir-Quickly** [comment]
Hi, no special tips I am aware.
But honestly I have not validated the layout since I use the handwired PCB.
But it should works.
on the multiplexer there different families available, I use the CD4053
successfully which is a analog switch rather tha a digital multiplexer.

The guys in the forum made a modification to my original schematic that the
Power of the hendi sets to min. if the PWM input from the Rhaspberry is
open.
I intentionally set to the maximum.

Hope it works finr for you



Am Mi., 2. Juni 2021 um 08:32 Uhr schrieb Dude ***@***.***>:

**Comment by heyudude** [comment]
Hi,
Small update. I used the pcb design and ordered it, added the bottom layer to the design.
I made it and mounted it in my Hendi 3500m. It works 👍🏼 great.
No issues, no diodes or anything else needed.
I use a control board of someone else's design, pwm signals.

Last Saturday I brewed a beer with it.
Thanks for the efforts publishing it.

Mvg

Dude

**Comment by Sir-Quickly** [comment]
Hi Dude,

thanks for the feedaback and I glad to hear that you have fun with it.

Take care,
Sir Quickly


Am Mo., 2. Aug. 2021 um 16:53 Uhr schrieb Dude ***@***.***>:

>
> Hi,
> Small update. I used the pcb design and ordered it, added the bottom layer
> to the design.
> I made it and mounted it in my Hendi 3500m. It works 👍🏼 great.
> No issues, no diodes or anything else needed.
> I use a control board of someone else's design, pwm signals.
>
> Last Saturday I brewed a beer with it.
> Thanks for the efforts publishing it.
>
> Mvg
>
> Dude
>

**Comment by Sir-Quickly** [comment]
fixed in latest version, added solder mask for bottom layer
